version: '3'
services: 
  userService: 
    #build: .
    image: github.com/docker/compose.git
    ports:
      - "3000:3000"
    #volumes:
      #- .:/opt
  mailService: 
    #build: .
    image: github.com/docker/compose.git
    ports:
      - "8080:8080"
  Database: 
    image: "mysql"
    ports:
      - "80:80"