version: '3'
services: 
  userService: 
    build: .
    #image: alepellereca/my-api:1.0.1
    ports:
      - "3000:3000"
    #volumes:
      #- .:/opt
  mailService: 
    build: .
    ports:
      - "8080:8080"
  Database: 
    image: deis
    ports:
      - "80:80"