#version: '3'
services: 
  user-service: 
    build: ./userService
    #image: alepellereca/my-api:1.0.1
    ports:
      - "3000:3000"
    #volumes:
      #- .:/opt
  mail-service: 
    build: ./mailService
    #image: alepellereca/my-api:1.0.1
    ports:
      - "8080:3000"
  redis:
    image: redis
 