version: '3'
services: 
  userService: 
    build: ./userService
    #image: alepellereca/my-api:1.0.1
    ports:
      - "3000:3000"
    #volumes:
      #- .:/opt
  mailService: 
    build: ./mailService
    #image: alepellereca/my-api:1.0.1
    ports:
      - "8080:3000"
  Database: 
    image: redis
    ports:
      - "5000:5000"
    volumes:
      - .:/code
 