services: 
  user-service: 
   build: ./userService
   volumes: 
    - .:/opt
   ports:
    - "3000:3000"
  mail-service: 
   build: ./mailService
   volumes: 
    - .:/opt
   ports:
    - "8080:3000"
